# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-02-22 18:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('market', '0009_DefaultBuyPriceIzZero'),
        ('crm', '0023_user_field_is_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_notice_date', models.DateField(blank=True, null=True, verbose_name='Last notice day')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer')),
            ],
            options={
                'verbose_name': 'Customer activity',
                'verbose_name_plural': 'Customer activities',
            },
        ),
    ]
