# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-02-22 18:31
from __future__ import unicode_literals

from django.db import migrations


def init_customer_activity(apps, schema_editor):
    Customer = apps.get_model('crm', 'Customer')
    Activity = apps.get_model('crm', 'Activity')
    for customer in Customer.objects.all():
        Activity.objects.create(customer=customer)


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0024_activity'),
    ]

    operations = [
        migrations.RunPython(init_customer_activity),
    ]
